/**
 * LANGUAGE REGISTRY
 * ---------------------------------------------------------------------------
 * Twelve languages. Each entry carries the endonym — the name of the language
 * *in* that language — because "Persian" means nothing to someone who only
 * reads Persian, and text direction, because getting RTL wrong makes an app
 * unusable rather than merely ugly.
 *
 * COVERAGE IS MEASURED, NOT DECLARED
 * There used to be a hand-written `complete: true` flag here. It claimed
 * Arabic was fully translated; in reality 686 of its 1,099 strings were still
 * the English sentence verbatim, because the file had been seeded from
 * en.json. A boolean somebody has to remember to update is a boolean that goes
 * stale, and a stale one here means telling users a language is finished when
 * they are about to meet English on most screens.
 *
 * So the numbers now come from `coverage.json`, regenerated by
 * `scripts/gen-locales.mjs`, which counts strings that actually DIFFER from
 * English. If the figure is wrong it is because the translations are wrong,
 * which is a fixable and visible problem.
 *
 * Untranslated strings fall back to English, never to a raw key: a visible
 * English sentence says "not translated yet", whereas `swap.err.NO_ROUTE`
 * says "this app is broken".
 */

import coverageData from './coverage.json';

/** 0-100, measured. Unknown languages report 0 rather than guessing. */
export const coverageFor = (code) => coverageData.coverage?.[code] ?? 0;

/** Threshold above which we stop flagging a language as partial. */
export const COMPLETE_AT = 90;

export const LANGUAGES = [
  { code: 'fa', name: 'Persian', endonym: 'فارسی', dir: 'rtl', flag: '🇮🇷' },
  { code: 'en', name: 'English', endonym: 'English', dir: 'ltr', flag: '🇬🇧' },
  { code: 'ar', name: 'Arabic', endonym: 'العربية', dir: 'rtl', flag: '🇸🇦' },
  { code: 'zh', name: 'Chinese', endonym: '中文', dir: 'ltr', flag: '🇨🇳' },
  { code: 'hi', name: 'Hindi', endonym: 'हिन्दी', dir: 'ltr', flag: '🇮🇳' },
  { code: 'es', name: 'Spanish', endonym: 'Español', dir: 'ltr', flag: '🇪🇸' },
  { code: 'fr', name: 'French', endonym: 'Français', dir: 'ltr', flag: '🇫🇷' },
  { code: 'ru', name: 'Russian', endonym: 'Русский', dir: 'ltr', flag: '🇷🇺' },
  { code: 'tr', name: 'Turkish', endonym: 'Türkçe', dir: 'ltr', flag: '🇹🇷' },
  { code: 'ur', name: 'Urdu', endonym: 'اردو', dir: 'rtl', flag: '🇵🇰' },
  { code: 'id', name: 'Indonesian', endonym: 'Bahasa Indonesia', dir: 'ltr', flag: '🇮🇩' },
  { code: 'pt', name: 'Portuguese', endonym: 'Português', dir: 'ltr', flag: '🇧🇷' }
];

export const SUPPORTED = LANGUAGES.map((l) => l.code);
export const RTL_LANGS = LANGUAGES.filter((l) => l.dir === 'rtl').map((l) => l.code);

export const langMeta = (code) => LANGUAGES.find((l) => l.code === code) ?? LANGUAGES[0];

/** True only when the measured coverage says so. */
export const isComplete = (code) => coverageFor(code) >= COMPLETE_AT;
export const isRtl = (code) => RTL_LANGS.includes(code);
