/** Provider-agnostic marketplace primitives. These engines only operate on verified
 * adapter payloads; unknown fields remain UNKNOWN rather than being inferred. */
export class InsuranceAggregator {
  constructor({ providers = [], now = () => Date.now() } = {}) { this.providers = providers; this.now = now; }
  async discover(requirement = {}) { const rows = []; for (const p of this.providers) { if (p.enabled === false || !p.adapter?.discoverProducts) continue; try { const products = await p.adapter.discoverProducts(requirement); for (const product of products || []) rows.push({ ...product, providerId: p.providerId, providerHealth: p.healthStatus || 'UNKNOWN' }); } catch { /* unavailable providers are not fabricated */ } } return rows; }
  normalizeQuote(q, provider = {}) { return { providerId: provider.providerId || q.providerId || 'UNKNOWN', productId: q.productId || 'UNKNOWN', coverageType: q.coverageType || q.kind || 'UNKNOWN', protocol: q.protocol || 'UNKNOWN', chain: q.chain || q.chainId || 'UNKNOWN', asset: q.asset || 'UNKNOWN', coverageAmount: q.coverageAmount ?? 'UNKNOWN', premium: q.premium ?? 'UNKNOWN', duration: q.duration ?? 'UNKNOWN', deductible: q.deductible ?? 'UNKNOWN', exclusions: q.exclusions || [], claimMethod: q.claimMethod || 'UNKNOWN', providerRisk: provider.riskScore ?? 'UNKNOWN', providerHealth: provider.healthStatus || 'UNKNOWN', capacity: q.capacity ?? 'UNKNOWN', termsHash: q.termsHash || 'UNKNOWN', expiresAt: q.expiresAt || null, source: q.source || 'provider-api', freshness: q.freshness || 'UNKNOWN' }; }
  async quote(requirement = {}) { const products = await this.discover(requirement); return products.filter(p => p.providerHealth === 'HEALTHY' || p.providerHealth === 'UNKNOWN'); }
}
export class InsuranceProviderRouter {
  rank(options = [], preferences = {}) { return options.filter(o => o.providerHealth !== 'UNAVAILABLE' && o.providerHealth !== 'PAUSED' && o.capacity !== 0).map(o => ({ ...o, routingScore: this.score(o, preferences) })).sort((a,b) => b.routingScore - a.routingScore); }
  score(o, pref = {}) { const premium = Number(o.premium) || Infinity; const coverage = Number(o.coverageAmount) || 0; const risk = Number(o.providerRisk); const deductible = Number(o.deductible) || 0; let s = Math.min(35, coverage / Math.max(1, Number(pref.requiredCoverage) || coverage) * 35) + Math.max(0, 25 - Math.min(25, premium / 100)) + Math.max(0, 20 - deductible / 100); if (Number.isFinite(risk)) s += Math.max(0, 20 - risk / 5); if (pref.preferredProviders?.includes(o.providerId)) s += 5; return Number(s.toFixed(2)); }
}
export class CoverageGapEngine { calculate(eligibleExposure, existingCoverage) { const eligible = Number(eligibleExposure) || 0; const existing = Number(existingCoverage) || 0; return { eligibleExposure: eligible, existingCoverage: existing, coverageGap: Math.max(0, eligible - existing), percentProtected: eligible ? Math.min(100, existing / eligible * 100) : 100 }; } }
export class ProtectionScore { calculate(o = {}) { const parts = { coverage: Number(o.coverageQuality) || 0, price: Number(o.price) || 0, providerRisk: Number(o.providerRisk) || 0, deductible: Number(o.deductibleScore) || 0, exclusions: Number(o.exclusionsScore) || 0, claims: Number(o.claimProcessScore) || 0, capacity: Number(o.capacityScore) || 0, duration: Number(o.durationScore) || 0, userFit: Number(o.userFit) || 0 }; const score = Math.round(Object.values(parts).reduce((a,b) => a+b, 0) / Object.keys(parts).length); return { score: Math.max(0, Math.min(100, score)), factors: parts, explanation: 'Weighted product factors; unavailable evidence is not treated as a positive claim.' }; } }
export class JurisdictionEligibilityEngine { evaluate({ region, provider, product } = {}) { if (!region || !provider || !product) return 'UNKNOWN'; if (product.restrictedRegions?.includes(region) || provider.restrictedRegions?.includes(region)) return 'UNAVAILABLE'; if (product.allowedRegions && !product.allowedRegions.includes(region)) return 'RESTRICTED'; return 'UNKNOWN'; } }
export class ProtectionProfile { constructor(values = {}) { Object.assign(this, { riskTolerance: 'UNKNOWN', preferredProviders: [], maxPremium: null, preferredDuration: null, preferredChains: [], minimumCoverage: null, autoRenew: false, notificationPreferences: {}, ...values }); } }
export class ClaimFraudEngine { inspect(claim, context = {}) { const reasons = []; if (context.claimIds?.includes(claim.claimId)) reasons.push('duplicate claim'); if (context.coverageExpired || context.outsideCoverage) reasons.push('coverage window invalid'); if (context.unsupportedProtocol) reasons.push('unsupported protocol'); if (!claim.evidenceHash || !claim.evidence) reasons.push('missing evidence'); return { status: reasons.length ? 'MANUAL_REVIEW' : 'PASS', reasons }; } }
