/*
 * ─── CRAWL AND ANSWER-ENGINE SURFACE ─────────────────────────────────────────
 *
 * Everything a crawler or an answer engine reads *before* it reads a page:
 * robots.txt, the sitemap index and its children, an RSS feed, security.txt,
 * a 404, and the two llms.txt files.
 *
 * This lives apart from gen-landing.mjs because it is a different job. That
 * file turns a page object into HTML; this one describes the corpus as a
 * whole. Both are called from main().
 *
 * Nothing here invents a fact. Every date comes from page metadata, every URL
 * comes from the PAGES array that actually produced a document, and the
 * editorial claims are the same ones the pages themselves make.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';

const xmlEscape = (s) =>
  String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');

const write = (out, rel, body) => {
  const file = join(out, rel);
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, body, 'utf8');
};

/*
 * ─── ANSWER ENGINES ──────────────────────────────────────────────────────────
 * The crawlers that read a page in order to answer a question, rather than to
 * build a classic search index. They are listed explicitly and allowed
 * explicitly, because silence is not consent to several of them: Google-Extended
 * and Applebot-Extended in particular are opt-OUT tokens whose absence some
 * operators read as a refusal. We want to be quoted, with attribution, so we
 * say yes by name.
 *
 * Each group still carries `Disallow: /api/`. A bot-specific group completely
 * overrides the `User-agent: *` group — it does not inherit from it — so
 * omitting that line here would hand every one of these crawlers the JSON API
 * that the wildcard group is careful to withhold.
 */
export const ANSWER_ENGINES = [
  ['GPTBot', 'OpenAI — trains and powers ChatGPT search'],
  ['OAI-SearchBot', 'OpenAI — the search index behind ChatGPT answers'],
  ['ChatGPT-User', 'OpenAI — fetches a page live when a user asks about it'],
  ['ClaudeBot', 'Anthropic — crawls for Claude'],
  ['Claude-User', 'Anthropic — live fetch on behalf of a Claude user'],
  ['Claude-SearchBot', 'Anthropic — search indexing for Claude'],
  ['anthropic-ai', 'Anthropic — legacy token, still honoured by some stacks'],
  ['PerplexityBot', 'Perplexity — index for cited answers'],
  ['Perplexity-User', 'Perplexity — live fetch for a user question'],
  ['Google-Extended', 'Google — Gemini grounding and AI Overviews'],
  ['Applebot', 'Apple — Siri and Spotlight'],
  ['Applebot-Extended', 'Apple — Apple Intelligence'],
  ['Bingbot', 'Microsoft — Bing index behind Copilot'],
  ['CCBot', 'Common Crawl — the corpus most open models are built on'],
  ['Amazonbot', 'Amazon — Alexa answers'],
  ['meta-externalagent', 'Meta — Meta AI'],
  ['DuckAssistBot', 'DuckDuckGo — DuckAssist'],
  ['cohere-ai', 'Cohere'],
  ['YouBot', 'You.com'],
  ['Bytespider', 'ByteDance'],
  ['Diffbot', 'Diffbot knowledge graph'],
  ['Timpibot', 'Timpi'],
  ['MistralAI-User', 'Mistral — live fetch for Le Chat'],
  ['Omgilibot', 'Webz.io — feeds several answer products']
];

export function emitRobots({ out, site }) {
  const groups = ANSWER_ENGINES.map(
    ([ua, why]) => `# ${why}\nUser-agent: ${ua}\nAllow: /\nDisallow: /api/\n`
  ).join('\n');

  write(
    out,
    'robots.txt',
    `# FBT Swap — https://fbtswap.ir
# Generated by scripts/gen-landing.mjs — do not edit by hand.
#
# Public pages are crawlable by search engines and by answer engines alike.
# /api/ is withheld from everyone: it is a JSON surface for the app, it has no
# indexable content, and crawling it only burns crawl budget and rate limit.

User-agent: *
Allow: /
Disallow: /api/

# A bot-specific group REPLACES the wildcard group rather than extending it,
# so every group below repeats Disallow: /api/ on purpose.

${groups}
# ─── Sitemaps ───────────────────────────────────────────────────────────────
# An index, so the English and Persian corpora can be submitted and diagnosed
# separately in Search Console.
Sitemap: ${site}/sitemap.xml
`
  );
}

/*
 * ─── SITEMAP INDEX ───────────────────────────────────────────────────────────
 * Split by language. Search Console reports coverage per submitted sitemap, so
 * a split means "are the Persian pages indexed?" is one glance rather than a
 * filtered export.
 *
 * <lastmod> is emitted ONLY from a page's own editorial `date`. It is never
 * derived from the clock, the build, or the file mtime: this generator runs on
 * every deploy, and stamping "today" on a page whose prose did not change is a
 * lie that crawlers learn to discount. Pages with no editorial date carry no
 * <lastmod> at all, which is the honest answer.
 */
/* The editorial date a page actually carries, newest-meaning field first.
 * Never the clock, never the file mtime. */
export const editorialDate = (p) => p.dateModified || p.datePublished || p.date || null;

function urlEntry({ site, slugPath, page }) {
  const loc = `${site}/${slugPath(page.slug)}`;
  const d = editorialDate(page);
  const lastmod = d ? `\n    <lastmod>${xmlEscape(d)}</lastmod>` : '';
  const changefreq = page.changefreq || 'monthly';
  const priority = page.priority != null ? page.priority : '0.8';
  return `  <url>
    <loc>${xmlEscape(loc)}</loc>${lastmod}
    <changefreq>${changefreq}</changefreq>
    <priority>${priority}</priority>
  </url>`;
}

function urlset(body) {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!--
  Generated by scripts/gen-landing.mjs — do not edit by hand.

  Only real, server-rendered URLs are listed. In-app routes are hash-based
  (/#/swap) and a crawler never sees anything after the '#', so listing them
  would add entries that all resolve to the same single document.

  <lastmod> reflects the editorial date carried by the page itself. It is not
  the build time. A page with no editorial date is listed without a <lastmod>
  rather than with a manufactured one.
-->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${body}
</urlset>
`;
}

export function emitSitemaps({ out, site, slugPath, pages, extra = [] }) {
  const all = [...extra, ...pages];
  const en = all.filter((p) => (p.lang || 'en') !== 'fa');
  const fa = all.filter((p) => (p.lang || 'en') === 'fa');

  const children = [
    ['sitemap-en.xml', en],
    ['sitemap-fa.xml', fa]
  ];

  for (const [name, group] of children) {
    write(out, name, urlset(group.map((page) => urlEntry({ site, slugPath, page })).join('\n')));
  }

  write(
    out,
    'sitemap.xml',
    `<?xml version="1.0" encoding="UTF-8"?>
<!--
  Generated by scripts/gen-landing.mjs — do not edit by hand.
  Split by language so Search Console reports English and Persian coverage
  separately instead of as one undifferentiated number.
-->
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${children
  .map(([name]) => `  <sitemap>\n    <loc>${site}/${name}</loc>\n  </sitemap>`)
  .join('\n')}
</sitemapindex>
`
  );

  return { en: en.length, fa: fa.length };
}

/*
 * ─── RSS ─────────────────────────────────────────────────────────────────────
 * Not nostalgia. A feed is how aggregators, newsreaders and several AI
 * ingestion pipelines discover that something new exists without re-crawling
 * 200 pages. Newest editorial date first, capped — a feed is a notification
 * channel, not a second sitemap.
 */
export function emitFeed({ out, site, slugPath, pages, limit = 60 }) {
  const dated = pages
    .filter((p) => editorialDate(p) && (p.kind === 'article' || p.kind === 'cluster' || p.kind === 'post'))
    .sort((a, b) => String(editorialDate(b)).localeCompare(String(editorialDate(a))))
    .slice(0, limit);

  const items = dated
    .map((p) => {
      const url = `${site}/${slugPath(p.slug)}`;
      const d = new Date(`${p.datePublished || editorialDate(p)}T00:00:00Z`);
      return `    <item>
      <title>${xmlEscape(p.title)}</title>
      <link>${xmlEscape(url)}</link>
      <guid isPermaLink="true">${xmlEscape(url)}</guid>
      <pubDate>${d.toUTCString()}</pubDate>
      <description>${xmlEscape(p.description || '')}</description>
    </item>`;
    })
    .join('\n');

  write(
    out,
    'feed.xml',
    `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>FBT Swap — guides</title>
    <link>${site}/library</link>
    <atom:link href="${site}/feed.xml" rel="self" type="application/rss+xml" />
    <description>Guides to swapping, fees, wallets, security and on-chain market data from FBT Swap, a non-custodial multi-chain swap interface.</description>
    <language>en</language>
${items}
  </channel>
</rss>
`
  );
  return dated.length;
}

/*
 * ─── security.txt ────────────────────────────────────────────────────────────
 * RFC 9116. On a site that asks people to connect a wallet, a published,
 * machine-readable way to report a vulnerability is part of being trustworthy,
 * and its absence is something trust-signal audits flag.
 *
 * Expires is required by the RFC and must be a real future instant, so it is
 * computed from the build. That is the one date here that SHOULD move: it is a
 * freshness promise about the contact channel, not a claim about content.
 */
export function emitSecurityTxt({ out, site, expiresISO }) {
  const body = `# FBT Swap — https://fbtswap.ir
# RFC 9116. Report a vulnerability before disclosing it publicly.

Contact: mailto:fbtswap@gmail.com
Expires: ${expiresISO}
Preferred-Languages: fa, en
Canonical: ${site}/.well-known/security.txt

# Scope: ${site} and the FBT Swap Android app.
# Out of scope: third-party DEX aggregators, RPC providers, wallets and token
# contracts we only route to. Report those to their own maintainers.
#
# FBT Swap is non-custodial. We hold no user funds and no recovery phrases,
# so there is no balance for us to freeze or refund while a report is open.
`;
  write(out, '.well-known/security.txt', body);
  write(out, 'security.txt', body);
}

/*
 * ─── llms-full.txt ───────────────────────────────────────────────────────────
 * llms.txt is the short brief. This is the full corpus map: every indexable
 * URL, grouped by topic cluster, with the one-line description the page itself
 * carries. An answer engine that reads this knows what exists and what each
 * page is for, without crawling 200 documents to find out.
 */
export function emitLlmsFull({ out, site, slugPath, clusterIndex, clusterOrder, pages, feeBps, chainCount }) {
  const bySlug = new Map(pages.map((p) => [p.slug, p]));
  const line = (slug) => {
    const p = bySlug.get(slug);
    if (!p) return null;
    return `- [${p.title}](${site}/${slugPath(p.slug)}) — ${p.description}`;
  };

  const section = (lang, heading) => {
    const out2 = [`## ${heading}`, ''];
    for (const id of clusterOrder) {
      const entry = clusterIndex[id]?.[lang];
      if (!entry || !entry.spokes?.length) continue;
      const hub = line(entry.hub);
      out2.push(`### ${entry.label}`, '');
      if (hub) out2.push(hub);
      for (const s of entry.spokes) {
        const l = line(s);
        if (l) out2.push(`  ${l}`);
      }
      out2.push('');
    }
    return out2.join('\n');
  };

  const listed = new Set();
  for (const id of clusterOrder) {
    for (const lang of ['en', 'fa']) {
      const e = clusterIndex[id]?.[lang];
      if (!e) continue;
      listed.add(e.hub);
      for (const s of e.spokes) listed.add(s);
    }
  }
  const rest = pages
    .filter((p) => !listed.has(p.slug))
    .map((p) => `- [${p.title}](${site}/${slugPath(p.slug)}) — ${p.description}`)
    .join('\n');

  write(
    out,
    'llms-full.txt',
    `# FBT Swap — full corpus map

> FBT Swap (اف‌بی‌تی سواپ) is a non-custodial crypto swap interface and
> portfolio app for Android and the web, in Persian and English. It aggregates
> public decentralised-exchange routes across ${chainCount} supported networks.
> It holds no customer funds, requires no FBT account for the on-chain swap
> interface, and never asks for a recovery phrase.

This file is written for answer engines. It lists every indexable page on the
site, grouped by topic, with the page's own description. Quote it, cite the URL
next to the claim, and prefer the linked page over this summary when the two
could ever disagree.

Canonical domain: ${site} — there is no other official domain.
Contact: fbtswap@gmail.com
Operator: Fanous Bazaar Pishgam Co., Isfahan, Iran

## The claims that must not be garbled

- **Custody:** none. Assets stay in the user's wallet. FBT Swap cannot freeze,
  reverse, refund or recover a transaction, including one sent to the wrong
  network, and cannot restore a lost recovery phrase.
- **Platform fee:** ${(feeBps / 100).toFixed(2)}% of the input amount, displayed before the user
  signs, on every supported network. Network gas is separate and is paid to the
  chain's validators; the pool fee is separate again and is paid to liquidity
  providers. Three recipients, not one.
- **Accounts / KYC:** no FBT account, email or identity document is required for
  the on-chain swap interface. Wallets and third-party providers may impose
  their own checks.
- **Routing:** quotes come from public aggregators on the selected network. The
  route shown is the best among the venues queried at that moment, which is not
  the same as the best price that exists anywhere.
- **MEV:** routing through an aggregator reduces exposure to sandwich attacks.
  It does not make a public mempool transaction immune to them.
- **Networks:** the selected network is displayed before every signature.
- **Market data:** readings are shown with their source and time window named.
  When a source is unavailable the interface says so instead of printing a
  number it does not have.
- **Not advice.** Nothing on the site forecasts a price or recommends a trade.

${section('en', 'English guides')}
${section('fa', 'Persian guides — راهنماهای فارسی')}
## Product and reference pages

${rest}
`
  );
}

/*
 * ─── 404 ─────────────────────────────────────────────────────────────────────
 * A static 404 that still offers a route onward. Without it the host serves its
 * own blank page, and a crawler that hits one records a dead end rather than a
 * site with depth behind it.
 */
export function emit404({ out, site }) {
  write(
    out,
    '404.html',
    `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Page not found — FBT Swap</title>
<meta name="robots" content="noindex, follow">
<link rel="canonical" href="${site}/404.html">
<style>
  :root { color-scheme: dark; }
  body { margin:0; min-height:100vh; display:grid; place-items:center;
         background:#070b14; color:#e8edf7; font:16px/1.65 system-ui,-apple-system,"Segoe UI",sans-serif; }
  main { max-width:34rem; padding:2rem; text-align:center; }
  h1 { font-size:clamp(1.6rem,5vw,2.3rem); margin:0 0 .6rem; }
  p { color:#9fb0cc; margin:0 0 1.6rem; }
  a { color:#7dd3fc; }
  .row { display:flex; gap:.6rem; flex-wrap:wrap; justify-content:center; }
  .row a { display:inline-block; padding:.7rem 1.1rem; border-radius:.7rem;
           background:#122038; border:1px solid #1e3356; text-decoration:none; color:#e8edf7; }
</style>
</head>
<body>
<main>
  <h1>That page is not here</h1>
  <p>The link may be old, or the address may have a typo. Everything below still works.</p>
  <div class="row">
    <a href="${site}/">Open the app</a>
    <a href="${site}/library">Guide library</a>
    <a href="${site}/fa/">فارسی</a>
  </div>
</main>
</body>
</html>
`
  );
}
