/* GENERATED by tools/build_audio.mjs — measured narration timings. */
export const NARRATION = [
  {
    "id": "sc01",
    "start": 6,
    "duration": 21,
    "end": 27
  },
  {
    "id": "sc02",
    "start": 46.5,
    "duration": 14.6,
    "end": 61.1
  },
  {
    "id": "sc03",
    "start": 84,
    "duration": 11.08,
    "end": 95.08
  },
  {
    "id": "sc04",
    "start": 124,
    "duration": 14.84,
    "end": 138.84
  },
  {
    "id": "sc05",
    "start": 174.5,
    "duration": 16.2,
    "end": 190.7
  },
  {
    "id": "sc06",
    "start": 233,
    "duration": 24.03,
    "end": 257.03
  },
  {
    "id": "sc07",
    "start": 296,
    "duration": 18.21,
    "end": 314.21
  },
  {
    "id": "sc08",
    "start": 352,
    "duration": 11.68,
    "end": 363.68
  },
  {
    "id": "sc09a",
    "start": 407.5,
    "duration": 6.19,
    "end": 413.69
  },
  {
    "id": "sc09b",
    "start": 443,
    "duration": 10.37,
    "end": 453.37
  },
  {
    "id": "sc10",
    "start": 460.5,
    "duration": 14.47,
    "end": 474.97
  },
  {
    "id": "sc11",
    "start": 502,
    "duration": 15.54,
    "end": 517.54
  },
  {
    "id": "sc12",
    "start": 552.5,
    "duration": 13.11,
    "end": 565.61
  },
  {
    "id": "sc13",
    "start": 579.2,
    "duration": 14.13,
    "end": 593.33
  }
];
export const narrationById = (id) => NARRATION.find((c) => c.id === id) || null;
