/**
 * Compiles contracts/FBTTokenFactory.sol -> src/lib/launch/artifacts.json
 * Run: node scripts/compile-launch.mjs
 *
 * Both contracts (FBTBasicToken + FBTTokenFactory) come from the same file,
 * one auditable surface. The artifact is consumed by:
 *   · src/lib/launch/calldata.js (the in-app launch engine)
 *   · server/launch.js (the public prepare API — same ABIs, same truth)
 *   · test/launch-probe.mjs (pinned against the real artifact)
 */
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const solc = require('solc');

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const source = fs.readFileSync(path.join(root, 'contracts/FBTTokenFactory.sol'), 'utf8');

const input = {
  language: 'Solidity',
  sources: { 'FBTTokenFactory.sol': { content: source } },
  settings: {
    optimizer: { enabled: true, runs: 200 },
    evmVersion: 'paris', // BSC-safe: avoids PUSH0 from Shanghai
    outputSelection: {
      '*': {
        '*': [
          'abi',
          'evm.bytecode.object',
          'evm.deployedBytecode.object',
          'evm.deployedBytecode.immutableReferences',
          'evm.gasEstimates'
        ]
      }
    }
  }
};

const out = JSON.parse(solc.compile(JSON.stringify(input)));
const errors = (out.errors || []).filter((e) => e.severity === 'error');
const warnings = (out.errors || []).filter((e) => e.severity === 'warning');

warnings.forEach((w) => console.log('⚠ ', w.formattedMessage.split('\n')[0]));
if (errors.length) {
  errors.forEach((e) => console.error(e.formattedMessage));
  process.exit(1);
}

function pick(contractName) {
  const c = out.contracts['FBTTokenFactory.sol'][contractName];
  return {
    contractName,
    abi: c.abi,
    bytecode: '0x' + c.evm.bytecode.object,
    deployedBytecode: '0x' + c.evm.deployedBytecode.object,
    immutableReferences: c.evm.deployedBytecode.immutableReferences || {},
    gasEstimates: c.evm.gasEstimates || {}
  };
}

const artifact = {
  version: 'fbt.launch-contracts.v1',
  compiler: solc.version(),
  evmVersion: 'paris',
  optimizer: { enabled: true, runs: 200 },
  contracts: {
    FBTBasicToken: pick('FBTBasicToken'),
    FBTTokenFactory: pick('FBTTokenFactory')
  }
};

const outDir = path.join(root, 'src/lib/launch');
fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(path.join(outDir, 'artifacts.json'), JSON.stringify(artifact, null, 2) + '\n');
/*
 * A .js twin of the same object, because the engine is imported by BOTH the
 * Vite browser bundle and the plain-Node server — and JSON import semantics
 * differ between the two (import attributes in Node, transformed modules in
 * Vite). One generated .js module keeps the ABIs byte-identical everywhere.
 */
fs.writeFileSync(
  path.join(outDir, 'artifacts.js'),
  '/* GENERATED by scripts/compile-launch.mjs — do not edit. */\nexport default ' +
    JSON.stringify(artifact, null, 2) +
    ';\n'
);

for (const name of ['FBTBasicToken', 'FBTTokenFactory']) {
  const a = artifact.contracts[name];
  console.log(`✓ compiled ${name}`);
  console.log(`  bytecode: ${(a.bytecode.length / 2 - 1)} bytes (limit 24576)`);
  console.log(`  functions: ${a.abi.filter((x) => x.type === 'function').length}`);
}
console.log('✓ wrote src/lib/launch/artifacts.json');
