#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# PUBLISH /.well-known/assetlinks.json — from the keystore, not from memory.
#
# Live measurement (2026-09-22, hours after every other wallet fix shipped):
#
#     https://fbtswap.ir/.well-known/assetlinks.json  →  404 NOT_FOUND
#
# Why it was 404 with everything else green: the file is only generated by
# `scripts/assetlinks.mjs --ensure` when FBT_ANDROID_SHA256 is present, and
# that variable exists in NO build environment — the APK workflow holds the
# keystore itself (ANDROID_KEYSTORE_BASE64), and Vercel holds neither. So the
# file was never written anywhere and Phantom/MWA kept answering
# «This app's identity could not be verified».
#
# This script closes the gap at the ONE place the real certificate already
# exists: the Build APK job. It
#   1. decodes the keystore the APK is signed with,
#   2. asks keytool for the SHA-256 certificate fingerprint(s),
#   3. writes public/.well-known/assetlinks.json through the SAME generator
#      the repo documents (scripts/assetlinks.mjs), so the format, the
#      package name (read from capacitor.config.json, not retyped) and the
#      validation rules stay single-sourced,
#   4. and commits it back to the current branch — but ONLY when the content
#      changed, so stable keys produce zero noise and no push-loop.
#
# TWO GUARANTEES THE STEP MUST KEEP (break either one and the file is worse
# than absent):
#   · Never invent, guess, or debug-sign a fingerprint. With no release
#     keystore in the environment the step SKIPS — it does not write.
#   · Never fail the job on a publish hiccup: the APK itself is the artifact
#     that matters; assetlinks is derived data and may be retried next push.
#     (fixing a real generator error is better than hiding it, though — the
#     generator's own validation errors ARE allowed to fail.)
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

TARGET="public/.well-known/assetlinks.json"
BRANCH="${GITHUB_REF_NAME:-$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo '')}"

if [ -z "${ANDROID_KEYSTORE_BASE64:-}" ] || [ -z "${ANDROID_KEYSTORE_PASSWORD:-}" ]; then
  echo "· assetlinks.json: no release keystore in this environment — skipping."
  echo "  (A fingerprint that is not the SHIPPED app's signing certificate"
  echo "   verifies nothing; the step refuses to publish one. Set the four"
  echo "   ANDROID_KEYSTORE_* secrets and the file appears on the next build.)"
  exit 0
fi

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > "$WORK/release.jks" 2>/dev/null \
  || echo "$ANDROID_KEYSTORE_BASE64" | base64 -D > "$WORK/release.jks"

ALIAS_ARGS=()
if [ -n "${ANDROID_KEY_ALIAS:-}" ]; then
  ALIAS_ARGS=(--alias="$ANDROID_KEY_ALIAS")
fi

# The generator refuses to write a value it could not read from the keystore,
# and validates the merged document before touching disk; both behaviours are
# load-bearing here.
node scripts/assetlinks.mjs --keystore="$WORK/release.jks" --storepass="$ANDROID_KEYSTORE_PASSWORD" "${ALIAS_ARGS[@]}"

# Also prove the committed copy — the one Vercel will serve — parses and
# matches the package this APK is built as.
node scripts/assetlinks.mjs --check

# Commit ONLY on real change. A stable keystore means exactly one commit,
# ever, and no later run pays a push.
if git ls-files --error-unmatch "$TARGET" >/dev/null 2>&1 && git diff --quiet -- "$TARGET"; then
  echo "✓ assetlinks.json already matches the signing keystore — nothing to commit."
  exit 0
fi

if [ -z "$BRANCH" ]; then
  echo "· assetlinks.json changed but the branch is detached — committing was skipped."
  exit 0
fi

git config user.name "fbt-build[bot]"
git config user.email "fbt-build[bot]@users.noreply.github.com"
git add "$TARGET"
# [skip ci] is deliberately ABSENT: Vercel must deploy the commit that first
# carries this file (that commit is the one that ends the 404). The loop
# cannot run anyway — the next job sees no diff and stops here.
git commit -m "ci: publish /.well-known/assetlinks.json from the release keystore"
git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}" "HEAD:${BRANCH}"
echo "✓ assetlinks.json committed on ${BRANCH} — deploys with the next web build."
